version: '3'

services:
  web:
    image: katsudon4919/manga_ocr_web:latest
    ports:
      - 80:80
    network_mode: "host"

  api:
    image: katsudon4919/manga_ocr_api:latest
    network_mode: "host"

  router:
    image: katsudon4919/manga_ocr_router:latest
    network_mode: "host"

  text_detection:
    image: katsudon4919/manga_ocr_textd:latest
    network_mode: "host"
  
  text_recognition:
    image: katsudon4919/manga_ocr_ocr:latest
    network_mode: "host"

  storage:
    image: katsudon4919/manga_ocr_storage:latest
    network_mode: "host"
    environment:
      - HTTP_HOST=127.0.0.1
      - HTTP_PORT=1606

networks:
  manga_ocr_network: